In [24]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import os
import sys

In [2]:
def Read_all_csv(folder_path):
    dataframe={}
    for file in glob.glob(os.path.join(folder_path,"*.csv")):
        name = file.split("\\")[-1].replace(".csv","")
        dataframe[name]=pd.read_csv(file)
    return dataframe

In [3]:
folder_path="D:\\DATA SETS (Project)\\Capston Project Data\\Financial Performence Analysis"
dfs=Read_all_csv(folder_path)
dfs.keys()

dict_keys(['Budget', 'Customers', 'Financial_Transactions', 'Headcount', 'Vendors'])

In [4]:
Budget = dfs['Budget']
Customers = dfs['Customers']
Financial_Transactions = dfs['Financial_Transactions']
Employees = dfs['Headcount']
Vendors = dfs['Vendors']

In [5]:
Budget.head()

   year  month business_unit  budgeted_revenue  budgeted_expense
0  2022      1        Retail           1530660           1259760
1  2022      1    Enterprise           1689240           1152615
2  2022      1        Online           2069088           1776169
3  2022      2        Retail           1836984           1201730
4  2022      2    Enterprise           1923012           1454263

In [6]:
Budget.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              72 non-null     int64
 1   month             72 non-null     int64
 2   business_unit     72 non-null     object
 3   budgeted_revenue  72 non-null     int64
 4   budgeted_expense  72 non-null     int64
dtypes: int64(4), object(1)
memory usage: 2.9+ KB

In [7]:
Budget.describe()

              year      month  budgeted_revenue  budgeted_expense
count    72.000000  72.000000      7.200000e+01      7.200000e+01
mean   2022.500000   6.500000      1.886305e+06      1.448129e+06
std       0.503509   3.476278      2.589688e+05      2.962708e+05
min    2022.000000   1.000000      1.447104e+06      9.066810e+05
25%    2022.000000   3.750000      1.646814e+06      1.228687e+06
50%    2022.500000   6.500000      1.917072e+06      1.411237e+06
75%    2023.000000   9.250000      2.110716e+06      1.671924e+06
max    2023.000000  12.000000      2.277540e+06      2.064497e+06

In [8]:
Budget["date"] = pd.to_datetime(Budget[["year","month"]].assign(day=1))
Budget.head()

   year  month business_unit  budgeted_revenue  budgeted_expense       date
0  2022      1        Retail           1530660           1259760 2022-01-01
1  2022      1    Enterprise           1689240           1152615 2022-01-01
2  2022      1        Online           2069088           1776169 2022-01-01
3  2022      2        Retail           1836984           1201730 2022-02-01
4  2022      2    Enterprise           1923012           1454263 2022-02-01

In [9]:
Customers.head()

  customer_id             customer_name     segment   join_date region  status
0   CUST10000  Johnson, Olson and Smith      Online  2020-03-28  North  Active
1   CUST10001              Colon-Valdez  Enterprise  2018-02-15   West  Active
2   CUST10002   Henry, Jones and Farley      Online  2022-03-21  North  Active
3   CUST10003           Williams-Dalton      Retail  2021-03-22   West  Active
4   CUST10004            Fisher-Serrano  Enterprise  2018-11-02   East  Active

In [10]:
Customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    400 non-null    object
 1   customer_name  400 non-null    object
 2   segment        400 non-null    object
 3   join_date      400 non-null    object
 4   region         400 non-null    object
 5   status         400 non-null    object
dtypes: object(6)
memory usage: 18.9+ KB

In [11]:
Customers["join_date"] = pd.to_datetime(Customers['join_date'])
Customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    400 non-null    object
 1   customer_name  400 non-null    object
 2   segment        400 non-null    object
 3   join_date      400 non-null    datetime64[ns]
 4   region         400 non-null    object
 5   status         400 non-null    object
dtypes: datetime64[ns](1), object(5)
memory usage: 18.9+ KB

In [12]:
Financial_Transactions.head()

,transaction_id,transaction_date,amount,account_type,category,business_unit,region,customer_id,vendor_id,description
0,TRX100000,2023-09-03,-66631.73,Expense,Supplies,Online,West,NaN,VEND1053,Begin catch control dark practice.
1,TRX100001,2023-09-13,-54305.58,Expense,Utilities,Enterprise,East,NaN,VEND1059,Style guy soldier boy energy above.
2,TRX100002,2023-06-27,146074.92,Revenue,Subscription,Online,East,CUST10122,NaN,Skill surface drug personal western.
3,TRX100003,2023-06-25,212157.95,Revenue,Service,Enterprise,West,CUST10027,NaN,Develop many it I rich floor decide.
4,TRX100004,2023-11-15,-35944.73,Expense,Rent,Enterprise,North,NaN,VEND1046,Choose thought teach never.

In [13]:
Financial_Transactions['amount_abs']=Financial_Transactions['amount'].abs()

In [14]:
Financial_Transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10400 entries, 0 to 10399
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10400 non-null  object
 1   transaction_date  10400 non-null  object
 2   amount            10400 non-null  float64
 3   account_type      10400 non-null  object
 4   category          10400 non-null  object
 5   business_unit     10400 non-null  object
 6   region            10400 non-null  object
 7   customer_id       5514 non-null   object
 8   vendor_id         4125 non-null   object
 9   description       10400 non-null  object
 10  amount_abs        10400 non-null  float64
dtypes: float64(2), object(9)
memory usage: 893.9+ KB

In [15]:
Financial_Transactions["transaction_date"] = pd.to_datetime(Financial_Transactions['transaction_date'])

In [16]:
Financial_Transactions.isnull().sum()

transaction_id         0
transaction_date       0
amount                 0
account_type           0
category               0
business_unit          0
region                 0
customer_id         4886
vendor_id           6275
description            0
amount_abs             0
dtype: int64

In [17]:
Financial_Transactions.groupby('account_type')[['customer_id','vendor_id']].count()

              customer_id  vendor_id
account_type
Asset                   0          0
Equity                  0          0
Expense                 0       4125
Liability               0          0
Revenue              5514          0

In [18]:
Financial_Transactions['account_type'].value_counts()

account_type
Revenue      5514
Expense      4125
Asset         315
Equity        244
Liability     202
Name: count, dtype: int64

In [19]:
Employees.head()

,employee_id,employee_name,business_unit,join_date,status,region,cost_to_company
0,EMP1000,Daniel Thornton,Enterprise,2023-02-11,Active,South,1566441
1,EMP1001,Ashley Burch,Retail,2020-09-10,Active,West,1533942
2,EMP1002,Angel Perry,Online,2022-02-28,Active,East,962333
3,EMP1003,Kimberly Harmon,Online,2021-10-15,Active,North,503403
4,EMP1004,Sarah Smith DDS,Enterprise,2023-01-31,Active,West,1051271

In [20]:
Employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      200 non-null    object
 1   employee_name    200 non-null    object
 2   business_unit    200 non-null    object
 3   join_date        200 non-null    object
 4   status           200 non-null    object
 5   region           200 non-null    object
 6   cost_to_company  200 non-null    int64
dtypes: int64(1), object(6)
memory usage: 11.1+ KB

In [21]:
Employees['join_date'] = pd.to_datetime(Employees['join_date'])

In [22]:
Vendors.head()

  vendor_id                vendor_name    category region active
0  VEND1000             Johnson-Howard    Supplies   East      Y
1  VEND1001                 Jensen Ltd  Consulting  South      Y
2  VEND1002              Collins Group    Services  North      Y
3  VEND1003    Smith, Kirby and Torres   Utilities  North      Y
4  VEND1004  Mcgrath, Wheeler and Boyd   Utilities  North      Y

In [23]:
Vendors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vendor_id    120 non-null    object
 1   vendor_name  120 non-null    object
 2   category     120 non-null    object
 3   region       120 non-null    object
 4   active       120 non-null    object
dtypes: object(5)
memory usage: 4.8+ KB